/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "outline": "#916f65",
        "on-surface": "#1b1b1c",
        "surface-container-highest": "#e5e2e1",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#fffbff",
        "primary": "#aa3000",
        "secondary-fixed": "#d6e4f4",
        "on-error": "#ffffff",
        "background": "#fcf9f8",
        "surface-variant": "#e5e2e1",
        "primary-container": "#d43f00",
        "surface-container-low": "#f6f3f2",
        "surface-container-high": "#eae7e7",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#5c4037",
        "on-error-container": "#93000a",
        "inverse-surface": "#303030",
        "on-secondary-fixed": "#0f1d28",
        "tertiary-container": "#d63c00",
        "on-primary-fixed-variant": "#852400",
        "tertiary-fixed-dim": "#ffb59f",
        "surface-tint": "#ae3200",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#f3f0ef",
        "outline-variant": "#e6beb2",
        "on-primary-fixed": "#3a0b00",
        "secondary": "#53606d",
        "on-tertiary-fixed-variant": "#862200",
        "primary-fixed-dim": "#ffb59e",
        "on-primary-container": "#fffbff",
        "tertiary-fixed": "#ffdbd1",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#bac8d7",
        "surface": "#fcf9f8",
        "tertiary": "#ab2e00",
        "on-background": "#1b1b1c",
        "inverse-primary": "#ffb59e",
        "on-secondary-container": "#596673",
        "primary-fixed": "#ffdbd0",
        "on-tertiary-fixed": "#3b0a00",
        "surface-container": "#f0eded",
        "on-secondary-fixed-variant": "#3b4855",
        "surface-dim": "#dcd9d9",
        "surface-bright": "#fcf9f8",
        "secondary-container": "#d6e4f4",
        "accent-dark": "#26333F",
        "brand-orange": "#FF4D00",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "section-gap": "120px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "gutter": "24px",
        "unit": "4px",
      },
      fontFamily: {
        "body-lg": ["Chivo", "sans-serif"],
        "headline-xl-mobile": ["Anton", "sans-serif"],
        "display-lg": ["Anton", "sans-serif"],
        "headline-md": ["Anton", "sans-serif"],
        "label-bold": ["Chivo", "sans-serif"],
        "body-md": ["Chivo", "sans-serif"],
        "price-display": ["Chivo", "sans-serif"],
        "headline-xl": ["Anton", "sans-serif"],
        "display": ["Anton", "sans-serif"],
        "body": ["Chivo", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-xl-mobile": ["48px", { lineHeight: "48px", fontWeight: "400" }],
        "display-lg": ["120px", { lineHeight: "110px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "36px", fontWeight: "400" }],
        "label-bold": ["14px", { lineHeight: "20px", letterSpacing: "0.1em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "price-display": ["24px", { lineHeight: "24px", fontWeight: "700" }],
        "headline-xl": ["72px", { lineHeight: "72px", fontWeight: "400" }],
      },
      keyframes: {
        fadeIn: { from: { opacity: 0, transform: "translateY(8px)" }, to: { opacity: 1, transform: "translateY(0)" } },
      },
      animation: {
        "fade-in": "fadeIn 0.3s ease forwards",
      },
    },
  },
  plugins: [],
};
